image_vis:
  - evi2
  - gcvi
  - kndvi
  - green

regions:
  - 1
  - 1

region_id_file:
# End years (i.e., 2020 = 2019 planting/harvest year)
# 2019 = 2018 CDL
# 2020 = 2019 CDL
# 2021 = 2020 CDL
# 2022 = 2021 CDL
years:
  - 2020
  - 2021
  - 2022

lc_path: !!null
