image_vis:
  - evi2
  - gcvi
  - kndvi

# The regions to process (start, end)
regions:
  - 1
  - 1

# The region file path
region_id_file: !!null

# End years (i.e., 2020 = 2019 planting/harvest year)
# 2019 = 2018 CDL
# 2020 = 2019 CDL
# 2021 = 2020 CDL
# 2022 = 2021 CDL
years:
  - 2020
  - 2021
  - 2022

# End year for prediction
predict_year: 2021
# Start and end date for prediction
# Set as !!null to use dates from filenames. However, it is recommended
# to set these dates to avoid unexpected date inclusions.
start_date: 07-01
end_date: 07-01
